#!/bin/sh
# postinst script for monitoring-plugins-abraflexi

set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi

    composer-debian monitoring-plugins-abraflexi

#DEBHELPER#

exit 0
